# Generated by Django 4.0.6 on 2022-09-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0015_dressingroom_actor_dressing'),
    ]

    operations = [
        migrations.AddField(
            model_name='dressingroom',
            name='floor',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='dressingroom',
            name='number',
            field=models.IntegerField(default=None),
        ),
    ]
